package database
 const ots_trade_delivery=`CREATE TABLE  ots_trade_delivery (
		delivery_id number(20) default 20000 not null  comment '发货编号' ,
		spp_spp_no varchar2(32)  not null  comment '供货商编号' ,
		spp_product_id number(10)  not null  comment '供货商商品编号' ,
		spp_delivery_no varchar2(32)    comment '供货商发货编号' ,
		spp_product_no varchar2(32)    comment '供货商商品编号' ,
		order_id number(20)  not null  comment '订单编号' ,
		mer_no varchar2(32)  not null  comment '商户编号' ,
		mer_product_id number(10)  not null  comment '商户商品编号' ,
		pl_id number(10)  not null  comment '产品线' ,
		carrier_no varchar2(8)  not null  comment '运营商' ,
		province_no varchar2(8)  not null  comment '省份' ,
		city_no varchar2(8)  not null  comment '城市' ,
		invoice_type number(3)  not null  comment '开票方式（1.不开发票，2.供货商开发票）' ,
		delivery_status number(3) default 20 not null  comment '发货状态' ,
		payment_status number(3) default 10 not null  comment '支付状态' ,
		create_time DATETIME default current_timestamp not null  comment '创建时间' ,
		face number(20,5)  not null  comment '商品面值' ,
		num number(10)  not null  comment '发货数量' ,
		total_face number(20,5)  not null  comment '发货总面值' ,
		cost_amount number(20,5)  not null  comment '发货成本' ,
		spp_fee_amount number(20,5)  not null  comment '供货商佣金' ,
		trade_fee_amount number(20,5)  not null  comment '发货服务费' ,
		payment_fee_amount number(20,5)  not null  comment '支付服务费' ,
		succ_face number(10)    comment '成功面值' ,
		start_time DATETIME    comment '开始时间' ,
		end_time DATETIME    comment '结束时间' ,
		return_msg varchar2(256)    comment '发货返回信息' ,
		request_params varchar2(2000)    comment '发货信息参数json' ,
		result_source number(1)    comment '发货结果来源（1：通知，2：查询，3：同步返回）' ,
		result_code varchar2(32)    comment '发货结果码' ,
		spp_product_cost number(20,5)    comment '供货商实际折扣' ,
		spp_order_no varchar2(32)    comment '供货商发货订单号' ,
		last_update_time DATETIME default current_timestamp not null  comment '最后更新时间' ,
		PRIMARY KEY (delivery_id)) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='订单发货表';`